from .proposal import get_proposal_agent_instruction
from .itinerary import get_itinerary_agent_instruction
from .brushup import get_brushup_agent_instruction
from .video import get_video_generation_prompt
from .image import get_image_generation_prompt
